Less branching in shaders, use dummy default texture instead
exception: normal map sampling - because need to know if material has no normal map to not recalculate TBN if unnecessary